package Main;
import java.util.ArrayList;
import java.util.List;

public class Datos {
    ArrayList<String> respuestas;
    ArrayList<String> palabras;
    ArrayList<String[]> palabrasComparacion;
    ArrayList<String[]> respuestasComparacion;
    boolean vacio;
    public Datos(int dificultad) {
        respuestas = new ArrayList<>();
        palabras = new ArrayList<>();
        palabrasComparacion = new ArrayList<String[]>();
        respuestasComparacion = new ArrayList<String[]>();
        if (dificultad == 1) {
            respuestas.add("aoi");
            respuestas.add("iie");
            respuestas.add("namae");
            respuestas.add("doko");
            respuestas.add("fune");
            respuestas.add("hon");
            respuestas.add("umi");
            respuestas.add("momo");
            respuestas.add("tsume");
            respuestas.add("sono");
            palabras.add("あおい");
            palabras.add("いいえ");
            palabras.add("なまえ");
            palabras.add("どこ");
            palabras.add("ふね");
            palabras.add("ほん");
            palabras.add("うみ");
            palabras.add("もも");
            palabras.add("つめ");
            palabras.add("その");
            String[] palabras1 = {"わ","れ","ね","ゆ"};
            palabrasComparacion.add(palabras1);
            String[] respuestas1 = {"wa - Hiragana", "re - Hiragana", "ne - Hiragana", "yu - Hiragana"};
            respuestasComparacion.add(respuestas1);
            String[] palabras2 = {"ら","ち","を","り"};
            palabrasComparacion.add(palabras2);
            String[] respuestas2 = {"ra - Hiragana", "chi - Hiragana", "wo - Hiragana", "ri - Hiragana"};
            respuestasComparacion.add(respuestas2);
            String[] palabras3 = {"ま","ほ","も","モ"};
            palabrasComparacion.add(palabras3);
            String[] respuestas3 = {"ma - Hiragana", "ho - Hiragana", "mo - Hiragana", "mo - Katakana"};
            respuestasComparacion.add(respuestas3);
            String[] palabras4 = {"た","に","け","い"};
            palabrasComparacion.add(palabras4);
            String[] respuestas4 = {"ta - Hiragana", "ni - Hiragana", "ke - Hiragana", "i - Hiragana"};
            respuestasComparacion.add(respuestas4);
            String[] palabras5 = {"さ","き","は","ち"};
            palabrasComparacion.add(palabras5);
            String[] respuestas5 = {"sa - Hiragana", "ki - Hiragana", "ha - Hiragana", "chi - Hiragana"};
            respuestasComparacion.add(respuestas5);
            String[] palabras6 = {"と","こ","て","ト"};
            palabrasComparacion.add(palabras6);
            String[] respuestas6 = {"to - Hiragana", "ko - Hiragana", "te - Hiragana", "to - Katakana"};
            respuestasComparacion.add(respuestas6);
            String[] palabras7 = {"あ","お","す","む"};
            palabrasComparacion.add(palabras7);
            String[] respuestas7 = {"a - Hiragana", "o - Hiragana", "su - Hiragana", "mu - Hiragana"};
            respuestasComparacion.add(respuestas7);
            //vacio = false;
        } else if (dificultad == 2) {
            respuestas.add("kotoba");
            respuestas.add("tomodachi");
            respuestas.add("kakkoii");
            respuestas.add("arigatou");
            respuestas.add("terebi");
            respuestas.add("moa");
            respuestas.add("raigetsu");
            respuestas.add("getsuyoubi");
            respuestas.add("pasokon");
            respuestas.add("kamera");
            palabras.add("ことば");
            palabras.add("ともだち");
            palabras.add("かっこいい");
            palabras.add("ありがとう");
            palabras.add("テレビ");
            palabras.add("モア");
            palabras.add("らいげつ");
            palabras.add("げつようび");
            palabras.add("パソコン");
            palabras.add("カメラ");
            //vacio = false;
        } else {
            respuestas.add("hanbaagaa");
            respuestas.add("muzukashii");
            respuestas.add("chokoreeto");
            respuestas.add("makudonarudo");
            respuestas.add("benkyoushimasu");
            respuestas.add("gomennasai");
            respuestas.add("konnichiha");
            respuestas.add("jidouhanbaiki");
            respuestas.add("natsuyasumi");
            respuestas.add("sandoicchi");
            palabras.add("ハンバーガー");
            palabras.add("むずかしい");
            palabras.add("チョコレート");
            palabras.add("マクドナルド");
            palabras.add("べんきょうします");
            palabras.add("ごめんなさい");
            palabras.add("こんにちは");
            palabras.add("じどうはんばいき");
            palabras.add("なつやすみ");
            palabras.add("サンドイッチ");
            //vacio = false;
        }
    }
}
